### ISSUE TITLE
Update to new law 2017

### ISSUE THREAD

**Issue by Trefex** [ggdn/monargent#1]
Hi,

Do you need any help to update the tool to new law from 2017?

Cheers,

**Comment by ggdn** [comment]
Hey,

It's planned to update the application to the new react version and the new law !
But i need time...
Do you want to participate by coding ?

**Comment by Trefex** [comment]
Yes, although I'm not a big expert on React.JS

I can help where needed though, if you give me tasks :D

**Comment by ggdn** [comment]
Updated ;)
